id = "codestackr"
name = "codeSTACKr theme"
version = "0.0.1"
schema_version = 1
authors = ["Pjort Kat"]
description = "A port of the popular codeSTACKr VS Code theme for Zed Editor"
repository = "https://github.com/Pjort/codestackr-zed"
